<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('users')->insert([											
            ['id'=>1,	'name'=>'中里　浩介',	'furigana'=>'ﾅｶｻﾄ ｺｳｽｹ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'k-nakazato@mail.kitami-it.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('k-nakazato'),	'jiss_share_id'=>'k-nakazato',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>2,	'name'=>'高尾　千穂',	'furigana'=>'ﾀｶｵ ﾁﾎ',	'gender'=>'女性',	'part'=>'科学／情報',	'email'=>'chihotakao@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('c-takao'),	'jiss_share_id'=>'c-takao',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>3,	'name'=>'石毛　勇介',	'furigana'=>'ｲｼｹﾞ ﾕｳｽｹ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'yusuke.ishige@nifty.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('y-ishige'),	'jiss_share_id'=>'y-ishige',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'全グループ'],
            ['id'=>4,	'name'=>'吉岡　伸輔',	'furigana'=>'ﾖｼｵｶ ｼﾝｽｹ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'yoshioka@idaten.c.u-tokyo.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('s-yoshioka'),	'jiss_share_id'=>'s-yoshioka',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>5,	'name'=>'長島　康敬',	'furigana'=>'ﾅｶﾞｼﾏ ﾔｽﾉﾘ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'yasunori.nagashima@nifty.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('y-nagashima'),	'jiss_share_id'=>'y-nagashima',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>6,	'name'=>'藤田　善也',	'furigana'=>'ﾌｼﾞﾀ ｾﾞﾝﾔ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'fujita.ski@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('z-fujita'),	'jiss_share_id'=>'z-fujita',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>7,	'name'=>'石橋　彩',	'furigana'=>'ｲｼﾊﾞｼ ｱﾔ',	'gender'=>'女性',	'part'=>'科学／情報',	'email'=>'aya-ishibashi@g.ecc.u-tokyo.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('a-ishibashi'),	'jiss_share_id'=>'a-ishibashi',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>8,	'name'=>'夏見　円',	'furigana'=>'ﾅﾂﾐ ﾏﾄﾞｶ',	'gender'=>'女性',	'part'=>'科学／情報',	'email'=>'natsu_mim@me.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('m-natsumi'),	'jiss_share_id'=>'m-natsumi',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門、saj_事務局'],
            ['id'=>9,	'name'=>'谷中　拓哉',	'furigana'=>'ﾔﾅｶ ﾀｸﾔ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'t.yanaka@shodai.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-yanaka'),	'jiss_share_id'=>'t-yanaka',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>10,	'name'=>'吉久　武志',	'furigana'=>'ﾖｼﾋｻ ﾀｹｼ',	'gender'=>'男性',	'part'=>'科学／情報',	'email'=>'ta01-yoshihisa@yspc.or.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-yoshihisa'),	'jiss_share_id'=>'t-yoshihisa',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_科学/情報部門'],
            ['id'=>11,	'name'=>'岡崎　若華',	'furigana'=>'ｵｶｻﾞｷ　ﾜｶﾅ',	'gender'=>'女性',	'part'=>'アンチ・ドーピング',	'email'=>'w70527@yahoo.co.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('w-okazaki'),	'jiss_share_id'=>'w-okazaki',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_アンチ・ドーピング部門'],
            ['id'=>12,	'name'=>'杉原　徳彦',	'furigana'=>'ｽｷﾞﾊﾗ ﾅﾙﾋｺ',	'gender'=>'男性',	'part'=>'アンチ・ドーピング',	'email'=>'n-sugihara@jinyu.or.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('n-sughihara'),	'jiss_share_id'=>'n-sughihara',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_アンチ・ドーピング部門'],
            ['id'=>13,	'name'=>'鈴木　聡',	'furigana'=>'ｽｽﾞｷ ｻﾄｼ',	'gender'=>'男性',	'part'=>'アンチ・ドーピング',	'email'=>'satoshi.s@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('s-suzuki'),	'jiss_share_id'=>'s-suzuki',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_アンチ・ドーピング部門'],
            ['id'=>14,	'name'=>'大塚　祥子',	'furigana'=>'ｵｵﾂｶ ｻﾁｺ',	'gender'=>'女性',	'part'=>'アンチ・ドーピング',	'email'=>'sachiko.o.369@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('s-otsuka'),	'jiss_share_id'=>'s-otsuka',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_アンチ・ドーピング部門'],
            ['id'=>15,	'name'=>'勝田　紘史',	'furigana'=>'ｶﾂﾀﾞ ﾋﾛｼ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'hkatsuda@heartful-health.or.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('h-katsuda'),	'jiss_share_id'=>'h-katsuda',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>16,	'name'=>'藤巻　良昌',	'furigana'=>'ﾌｼﾞﾏｷ ﾖｼﾏｻ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'makio4403@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('y-fujimaki'),	'jiss_share_id'=>'y-fujimaki',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>17,	'name'=>'小岩　空',	'furigana'=>'ｺｲﾜ ｿﾗ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'small.rock.sky@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('s-koiwa'),	'jiss_share_id'=>'s-koiwa',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>18,	'name'=>'相澤　充',	'furigana'=>'ｱｲｻﾞﾜ ﾐﾂﾙ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'aizawa.mitsuru@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('m-aizawa'),	'jiss_share_id'=>'m-aizawa',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>19,	'name'=>'神谷　智昭',	'furigana'=>'ｶﾐﾔ ﾄﾓｱｷ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'tkamiya0606@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-kamiya'),	'jiss_share_id'=>'t-kamiya',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>20,	'name'=>'川上　良明',	'furigana'=>'ｶﾜｶﾐ ﾖｼｱｷ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'kawakamiyoshiaki@tdc.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('y-kawakami'),	'jiss_share_id'=>'y-kawakami',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>21,	'name'=>'古賀　英之',	'furigana'=>'ｺｶﾞ ﾋﾃﾞﾕｷ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'koga.orj@tmd.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('h-koga'),	'jiss_share_id'=>'h-koga',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>22,	'name'=>'後藤　和海',	'furigana'=>'ｺﾞﾄｳ ｶｽﾞﾐ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'a050017@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('k-goto'),	'jiss_share_id'=>'k-goto',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>23,	'name'=>'白土　貴史',	'furigana'=>'ｼﾗﾄ ﾀｶｼ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'takashi.shirato@nifty.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-shirato'),	'jiss_share_id'=>'t-shirato',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>24,	'name'=>'武田　友孝',	'furigana'=>'ﾀｹﾀﾞ ﾄﾓﾀｶ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'ttakeda@tdc.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-takeda'),	'jiss_share_id'=>'t-takeda',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>25,	'name'=>'田畑　尚吾',	'furigana'=>'ﾀﾊﾞﾀ ｼｮｳｺﾞ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'sky_walker_590718@yahoo.co.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('s-tabata'),	'jiss_share_id'=>'s-tabata',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>26,	'name'=>'寺本　篤史',	'furigana'=>'ﾃﾗﾓﾄ ｱﾂｼ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'teramoto.atsushi@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('a-teramoto'),	'jiss_share_id'=>'a-teramoto',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>27,	'name'=>'藤木　崇史',	'furigana'=>'ﾌｼﾞｷ ﾀｶﾌﾐ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'fjk2647@river.ocn.ne.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-fujiki'),	'jiss_share_id'=>'t-fujiki',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>28,	'name'=>'渡邉　耕太',	'furigana'=>'ﾜﾀﾅﾍﾞ ｺｳﾀ',	'gender'=>'男性',	'part'=>'ドクター',	'email'=>'wkota@sapmed.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('k-watanabe'),	'jiss_share_id'=>'k-watanabe',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_ドクター部門'],
            ['id'=>29,	'name'=>'柏木　久美子',	'furigana'=>'ｶｼﾜｷﾞ ｸﾐｺ',	'gender'=>'女性',	'part'=>'トレーナー',	'email'=>'kumi10095593@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('k-kashiwaghi'),	'jiss_share_id'=>'k-kashiwaghi',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>30,	'name'=>'瀬戸口　淳',	'furigana'=>'ｾﾄｸﾞﾁ ｼﾞｭﾝ',	'gender'=>'男性',	'part'=>'トレーナー',	'email'=>'setoguchi324@icloud.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('j-setoguchi'),	'jiss_share_id'=>'j-setoguchi',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>31,	'name'=>'安岡　淳智',	'furigana'=>'ﾔｽｵｶ ﾀﾀﾞﾄｼ',	'gender'=>'男性',	'part'=>'トレーナー',	'email'=>'t.yasuoka7@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('t-yasuoka'),	'jiss_share_id'=>'t-yasuoka',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>32,	'name'=>'藤原　良次',	'furigana'=>'ﾌｼﾞﾜﾗ ﾘｮｳｼﾞ',	'gender'=>'男性',	'part'=>'トレーナー',	'email'=>'fujiwara.trainer@gmail.com',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('r-fujiwara'),	'jiss_share_id'=>'r-fujiwara',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>33,	'name'=>'寒川　美奈',	'furigana'=>'ｻﾑｶﾜ ﾐﾅ',	'gender'=>'女性',	'part'=>'トレーナー',	'email'=>'mina@hs.hokudai.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('m-samukawa'),	'jiss_share_id'=>'m-samukawa',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>34,	'name'=>'谷口　圭吾',	'furigana'=>'ﾀﾆｸﾞﾁ ｹｲｺﾞ',	'gender'=>'男性',	'part'=>'トレーナー',	'email'=>'ktani@sapmed.ac.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('k-taniguchi'),	'jiss_share_id'=>'k-taniguchi',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>35,	'name'=>'綿谷　美佐子',	'furigana'=>'ﾜﾀﾔ ﾐｻｺ',	'gender'=>'女性',	'part'=>'トレーナー',	'email'=>'tereteremisa@yahoo.co.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('m-wataya'),	'jiss_share_id'=>'m-wataya',	'role'=>'0',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_トレーナー部門'],
            ['id'=>36,	'name'=>'磯谷　寛幸',	'furigana'=>'ｲｿｶﾞｲ ﾋﾛﾕｷ',	'gender'=>'男性',	'part'=>'事務局',	'email'=>'h.isogai@ski-japan.or.jp',	'email_verified_at'=>Carbon::now(),	'password'=> Hash::make('h-isogai'),	'jiss_share_id'=>'h-isogai',	'role'=>'1',	'jiss_share_group'=>'saj_ims',	'affiliation'=>'saj_事務局']
            ]);											
            
    }
}
